name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APK_PATH: build/app/outputs/flutter-apk/app-release.apk
      AAB_PATH: build/app/outputs/bundle/release/app-release.aab

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.2

      - run: flutter pub get
      
      - run: flutter build apk
      
      - run: flutter build appbundle

      # Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: ${{ env.APK_PATH }}
      
      # Upload AAB as an artifact
      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-release-aab
          path: ${{ env.AAB_PATH }}

      # Create a Git Tag
      - name: Create Git Tag
        run: |
          echo "Creating Git tag"
          git tag v1.0.0
          git push origin v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      # Create a GitHub release and upload the APK and AAB files
      - name: Create Release and Upload Files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.APK_PATH }}
            ${{ env.AAB_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
