name: Flutter Android CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.5.2' # specify your Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Run Flutter tests
      run: flutter test

    - name: Build APK for Android
      run: flutter build apk --release

    - name: Upload Android APK
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk
