name: Android Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    # If you want to build an AAB instead of APK, replace the above step with:
    # - name: Build AAB
    #   run: flutter build appbundle --release

    - name: Upload APK to GitHub Releases
      uses: actions/upload-artifact@v3
      with:
        name: android-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        # For AAB, use the following path instead:
        # path: build/app/outputs/bundle/release/app-release.aab

    # Optional: Create a GitHub release and upload the artifact
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/app-release.apk"  # Use app-release.aab for AAB builds
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: |
          This is the release APK for Android.
        draft: false
        prerelease: false
